export const ROUTES = {
  AUTH: {
    BASE: "/auth",
    SIGNUP: "/signup",
    LOGIN: "/login",
    GOOGLE_LOGIN: "/login/google",
    GOOGLE_CALLBACK: "/login/google/callback",
    REFRESH_TOKEN: "/refresh-token",
    SEND_VERIFY_EMAIL: "/send-verify-email",
    VERIFY_EMAIL: "/verify-email",
    SEND_FORGOT_PASSWORD_OTP: "/forgot-password",
    VERIFY_FORGOT_PASSWORD_OTP: "/forgot-password/verify-otp",
    RESET_PASSWORD: "/reset-password",
    CHANGE_PASSWORD: "/change-password",
  },
  USER: {
    BASE: "/user",
    LOGOUT: "/logout",
    CHANGE_AVATAR: "/change-avatar",
    DELETE_AVATAR: "/delete-avatar",
    PROFILE: "/profile",
    PUBLIC_PROFILE: "/profile/:id",
    UPDATE_PROFILE: "/update-profile",
    EXPERIENCE: "/experience",
    EXPERIENCE_ITEM: "/experience/:id",
    EDUCATION: "/education",
    EDUCATION_ITEM: "/education/:id",
    SEND_CHANGE_EMAIL_OTP: "/change-email/send-otp",
    CHANGE_EMAIL: "/change-email",
    CHANGE_CV: "/change-cv",
    DELETE_CV: "/delete-cv",
    SEND_DELETE_ACCOUNT_OTP: "/delete-account/send-otp",
    DELETE_ACCOUNT: "/delete-account",
  },
  COMPANY: {
    BASE: "/company",
    COMPANY_APPLLICATION: "/application",
    COMPANY_PROFILE: "/profile",
    COMPANY_JOBS: "/:companyId/jobs",
  },
  APPLICATION: {
    BASE: "/application",
    USER_APPLICATIONS: "/me",
    APPLICATION_ITEM: "/:id",
    WITHDRAW_APPLICATION: "/:id/withdraw",
    APPLICANTS_NOTE: "/:id/notes",
  },
  JOB: {
    BASE: "/job",
    JOB_ITEM: "/:id",
    JOB_APPLICATION: "/:id/application",
    JOBS: "/jobs",
    COMPANY_JOBS: "/company/:companyId/jobs",
    JOB_PUBLISH: "/:id/publish",
    JOB_CLOSE: "/:id/close",
    JOB_APPLICATIONS: "/:id/applications",
  },
  SAVED_JOB: {
    BASE: "/save",
    SAVE_ITEM: "/:id",
  },
  REPORT: {
    BASE: "/report",
    REPORT_COMPANY: "/company/:id",
    REPORT_USER: "/user/:id",
  },
  INTERVIEW:{
    BASE:"/interview",
    ROOT:"/",
    USER_INTERVIEWS:"/me",
    COMPANY_INTERVIEW:"/:id",
    INTERVIEW_ITEM:"/:id",

  }
} as const;
