export const ROUTES = {
  AUTH: {
    BASE: "/auth",
    SIGNUP: "/signup",
    LOGIN: "/login",
    GOOGLE_LOGIN: "/login/google",
    GOOGLE_CALLBACK: "/login/google/callback",
    REFRESH_TOKEN: "/refresh-token",
    SEND_VERIFY_EMAIL: "/send-verify-email",
    VERIFY_EMAIL: "/verify-email",
    SEND_FORGOT_PASSWORD_OTP: "/forgot-password",
    VERIFY_FORGOT_PASSWORD_OTP: "/forgot-password/verify-otp",
    RESET_PASSWORD: "/reset-password",
    CHANGE_PASSWORD: "/change-password",
  },
  USER: {
    BASE: "/user",
    LOGOUT: "/logout",
    CHANGE_AVATAR: "/change-avatar",
    DELETE_AVATAR: "/delete-avatar",
    PROFILE: "/profile",
    PUBLIC_PROFILE: "/profile/:id",
    UPDATE_PROFILE: "/update-profile",
    EXPERIENCE: "/experience",
    EXPERIENCE_ITEM: "/experience/:id",
    EDUCATION: "/education",
    EDUCATION_ITEM: "/education/:id",
    SEND_CHANGE_EMAIL_OTP: "/change-email/send-otp",
    CHANGE_EMAIL: "/change-email",
    CHANGE_CV: "/change-cv",
    DELETE_CV: "/delete-cv",
    SEND_DELETE_ACCOUNT_OTP: "/delete-account/send-otp",
    DELETE_ACCOUNT: "/delete-account",
  },
  COMPANY: {
    BASE: "/company",
    COMPANY_APPLLICATION: "/application",
    COMPANY_PROFILE: "/profile",
    COMPANY_JOBS: "/:companyId/jobs",
  },
  APPLICATION: {
    BASE: "/applcation",
  },
  JOB: {
    BASE: "/job",
    JOB_ITEM: "/:id",
    JOBS: "/jobs",
    COMPANY_JOBS: "/company/:companyId/jobs",
  },
} as const;
